// <auto-generated />
namespace Lis.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DoctorDesignationSignature : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DoctorDesignationSignature));

        string IMigrationMetadata.Id => "202606281200000_DoctorDesignationSignature";

        string IMigrationMetadata.Source => null;

        string IMigrationMetadata.Target => Resources.GetString("Target");
    }
}
