// <auto-generated />
namespace LIS.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PatientMrVisitPrefix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PatientMrVisitPrefix));

        string IMigrationMetadata.Id
        {
            get { return "202606271200000_PatientMrVisitPrefix"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
