// <auto-generated />
namespace LIS.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ReportTemplateEngine : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReportLayoutConfiguration));

        string IMigrationMetadata.Id
        {
            get { return "202609121600000_ReportTemplateEngine"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            // Reuse prior model snapshot; schema applied via raw SQL (same pattern as layout feature).
            get { return Resources.GetString("Target"); }
        }
    }
}
