// <auto-generated />
namespace LIS.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class LabResultRestructure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LabResultRestructure));

        string IMigrationMetadata.Id => "202607081220000_LabResultRestructure";

        string IMigrationMetadata.Source => null;

        string IMigrationMetadata.Target => Resources.GetString("Target");
    }
}
