USE [LISStaging]
GO

/****** Object:  Table [dbo].[ExecutionLog]    Script Date: 5/26/2024 11:29:07 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ExecutionLog](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ProcudereName] [varchar](255) NOT NULL,
	[Description] [varchar](255) NOT NULL,
	[ExecutedOn] [datetime] NOT NULL,
 CONSTRAINT [PK_ExecutionLog] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


